title: Just the Docs Exercise
description: Just the Docs Exercise
theme: just-the-docs
color_scheme: dark
url: https://martasko24.github.io/Just-the-docs

aux_links:
  Template Repository: https://github.com/martasko24/Just-the-docs
